/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;


import java.io.File;

import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import model.Employee;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import model.EmployeeHistory;



/**
 *
 * @author shreya baliga
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    EmployeeHistory emphistory;
    String filePath="";
    public CreateJPanel(EmployeeHistory emphistory) {
        initComponents();
        
       this.emphistory= emphistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_create = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        lbl_age = new javax.swing.JLabel();
        txt_age = new javax.swing.JTextField();
        lbl_gender = new javax.swing.JLabel();
        lbl_level = new javax.swing.JLabel();
        txt_level = new javax.swing.JTextField();
        lbl_teaminfo = new javax.swing.JLabel();
        txt_teaminfo = new javax.swing.JTextField();
        lbl_pos = new javax.swing.JLabel();
        txt_pos = new javax.swing.JTextField();
        lbl_date = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();
        jCmbBox = new javax.swing.JComboBox<>();
        lbl_profile = new javax.swing.JLabel();
        btn_choosefile = new javax.swing.JButton();

        lbl_create.setText("                                               CREATE");

        lbl_name.setText("NAME:");

        lbl_id.setText("EMPLOYEE ID:");

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        lbl_age.setText("AGE:");

        lbl_gender.setText("GENDER:");

        lbl_level.setText("LEVEL:");

        lbl_teaminfo.setText("TEAM INFO:");

        lbl_pos.setText("POSITION TITLE:");

        lbl_date.setText("DATE:");

        jCmbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Your Gender", "FEMALE", "MALE", "OTHER" }));
        jCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBoxActionPerformed(evt);
            }
        });

        lbl_profile.setText("PROFILE PICTURE:");

        btn_choosefile.setText("Choose picture");
        btn_choosefile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_choosefileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_pos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_age, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_level, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_teaminfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbl_profile))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jCmbBox, 0, 217, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_name)
                                            .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                            .addComponent(txt_age)
                                            .addComponent(txt_level)
                                            .addComponent(txt_teaminfo))))
                                .addGap(0, 294, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_pos)
                                    .addComponent(txt_date)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_choosefile, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(309, 309, 309)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(btn_save)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_create)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_age, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_gender)
                    .addComponent(jCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_level)
                    .addComponent(txt_level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_teaminfo)
                    .addComponent(txt_teaminfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pos)
                    .addComponent(txt_pos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_date)
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_profile)
                    .addComponent(btn_choosefile))
                .addGap(52, 52, 52)
                .addComponent(btn_save)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_idActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        Employee emp = emphistory.addnewEmployee();
        String name = txt_name.getText();
        String id=txt_id.getText();
        String age=(String)txt_age.getText();
        String gender=(String)jCmbBox.getSelectedItem();
        String date=txt_date.getText();
        String level=(String)txt_level.getText();
        String position=txt_pos.getText();
        String teaminfo=txt_teaminfo.getText();
        String path=filePath;
        //String image = emp.getImage();
        emp.setName(name);
        emp.setId(id);
        emp.setAge(Integer.parseInt(age));
        emp.setDate(date);
        emp.setLevel(Integer.parseInt(level));
        emp.setPos_title(position);
        emp.setTeam_info(teaminfo);
        emp.setGender(gender);
        emp.setImage(path);
        
        
        //JOptionPane.showMessageDialog(this, "saved successfully","SAVE", HEIGHT);
         txt_name.setText("");
         txt_id.setText("");
         jCmbBox.setSelectedIndex(0);
         txt_age.setText("");
         txt_date.setText("");
         txt_level.setText("");
         txt_pos.setText("");
         txt_teaminfo.setText("");
         
         //lbl_picture.setText("");
//        emphist.setName(txt_name.getText());
//       emphist.setId(txt_id.getText());
       
       JOptionPane.showMessageDialog(this, "saved successfully","SAVE", HEIGHT);
    }//GEN-LAST:event_btn_saveActionPerformed

    private void jCmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBoxActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jCmbBoxActionPerformed

    private void btn_choosefileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_choosefileActionPerformed
        // TODO add your handling code here:
         filePath = retrieveImage();
//        JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
//        int r = j.showOpenDialog(null);
//        j.addChoosableFileFilter(new ImageFilter());
//            j.setAcceptAllFileFilterUsed(false);
//        
//        if (r == JFileChooser.APPROVE_OPTION) {
//                // set the label to the path of the selected directory
//                File file = j.getSelectedFile();
//                lbl_picture.setText("File Selected: " + file.getName());
//            }
//            // if the user cancelled the operation
//            else
//                lbl_picture.setText("the user cancelled the operation");
//        
    }//GEN-LAST:event_btn_choosefileActionPerformed
//     private void btnSaveActionPerformed(java.awt.event.ActionEvent evt)
//     {
//         emp.setName(txtName.getText());
//     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_choosefile;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> jCmbBox;
    private javax.swing.JLabel lbl_age;
    private javax.swing.JLabel lbl_create;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_gender;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_level;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_pos;
    private javax.swing.JLabel lbl_profile;
    private javax.swing.JLabel lbl_teaminfo;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_level;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_pos;
    private javax.swing.JTextField txt_teaminfo;
    // End of variables declaration//GEN-END:variables

   public String retrieveImage()
   {
     JFileChooser j = new JFileChooser();
     j.showOpenDialog(null);
    // j.addChoosableFileFilter(new ImageFilter());
     File file=j.getSelectedFile();
     String path=file.getAbsolutePath();
     return path;  
   }
}

