/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Employee;
import model.EmployeeHistory;

/**
 *
 * @author shreya baliga
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    EmployeeHistory emphistory;
    Employee emp;
    public ViewJPanel(EmployeeHistory emphistory) {
        initComponents();
        this.emphistory=emphistory;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_view = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        lbl_name = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lbl_date = new javax.swing.JLabel();
        txt_age = new javax.swing.JTextField();
        txt_date = new javax.swing.JTextField();
        lbl_gender = new javax.swing.JLabel();
        lbl_level = new javax.swing.JLabel();
        txt_level = new javax.swing.JTextField();
        lbl_teaminfo = new javax.swing.JLabel();
        txt_teaminfo = new javax.swing.JTextField();
        lbl_pos = new javax.swing.JLabel();
        lbl_age = new javax.swing.JLabel();
        txt_pos = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        txt_gender = new javax.swing.JTextField();
        lbl_pic = new javax.swing.JLabel();
        jbtnSaveAfterUpdate = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        lbl_search = new javax.swing.JLabel();

        setName("viewjpanel"); // NOI18N

        lbl_view.setText("                                                       VIEW");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NAME:", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        lbl_name.setText("NAME:");

        lbl_id.setText("EMPLOYEE ID:");

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        btnView.setText("VIEW");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lbl_date.setText("DATE:");

        lbl_gender.setText("GENDER:");

        lbl_level.setText("LEVEL:");

        lbl_teaminfo.setText("TEAM INFO:");

        txt_teaminfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_teaminfoActionPerformed(evt);
            }
        });

        lbl_pos.setText("POSITION TITLE:");

        lbl_age.setText("AGE:");

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lbl_pic.setText("PROFILE PICTURE:");

        jbtnSaveAfterUpdate.setText("SAVE");
        jbtnSaveAfterUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveAfterUpdateActionPerformed(evt);
            }
        });

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        lbl_search.setText("SEARCH:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(182, 182, 182))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(btnView)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbl_pos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(lbl_date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_pos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_level, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_level))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_teaminfo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_teaminfo)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lbl_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbl_age, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbl_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                            .addComponent(txt_age)
                                            .addComponent(txt_name))))
                                .addGap(31, 31, 31)
                                .addComponent(lbl_pic, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_search, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnSaveAfterUpdate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_view)
                    .addComponent(lbl_search, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnDelete))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_pic, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_age, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_gender)
                    .addComponent(txt_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_level)
                    .addComponent(txt_level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_teaminfo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_teaminfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pos)
                    .addComponent(txt_pos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_date)
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(jbtnSaveAfterUpdate))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = table.getSelectedRow();
        if(selectedRowIndex<0)
        {
            JOptionPane.showMessageDialog(this,"Please select a row to view");
            return;
        }
        
        DefaultTableModel mod = (DefaultTableModel)table.getModel();
        
        Employee selectedemployee = (Employee)mod.getValueAt(selectedRowIndex,0);
        txt_name.setText(selectedemployee.getName());
        txt_id.setText(selectedemployee.getId());
        txt_gender.setText(selectedemployee.getGender());
        txt_age.setText(Integer.toString(selectedemployee.getAge()));
         txt_date.setText(selectedemployee.getDate());
         txt_level.setText(Integer.toString(selectedemployee.getLevel()));
         txt_pos.setText(selectedemployee.getPos_title());
         txt_teaminfo.setText(selectedemployee.getTeam_info());
         
//         CreateJPanel create = new CreateJPanel();
//         String filepath = create.filePath;
         
         Image im =Toolkit.getDefaultToolkit().createImage(selectedemployee.getImage());
         im=im.getScaledInstance(lbl_pic.getWidth(),lbl_pic.getHeight(),Image.SCALE_SMOOTH);
         ImageIcon ii=new ImageIcon(im);
         lbl_pic.setIcon(ii);
         
       
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = table.getSelectedRow();
        if(selectedRowIndex<0)
        {
            JOptionPane.showMessageDialog(this,"Please select a row to delete");
            return;
        }
        
        DefaultTableModel mod = (DefaultTableModel)table.getModel();
        
        Employee selectedemployee = (Employee)mod.getValueAt(selectedRowIndex,0);
        emphistory.deleteEmployee(selectedemployee);
        
        JOptionPane.showMessageDialog(this,"Employee details deleted");
        txt_name.setText("");
         txt_id.setText("");
         txt_age.setText("");
         txt_date.setText("");
         txt_level.setText("");
         txt_pos.setText("");
         txt_teaminfo.setText("");
         txt_gender.setText("");
         
         
        populateTable();
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = table.getSelectedRow();
        if(selectedRowIndex<0)
        {
            JOptionPane.showMessageDialog(this,"Please select a row to Update");
            return;
        }
        
        DefaultTableModel mod = (DefaultTableModel)table.getModel();
        
        Employee selectedEmployee = (Employee)mod.getValueAt(selectedRowIndex,0);
        
    
        String name = txt_name.getText();
        String id=txt_id.getText();
        String age=(String)txt_age.getText();
        String gender=(String)txt_gender.getText();
        String date=txt_date.getText();
        String level=txt_level.getText();
        String position=txt_pos.getText();
        String teaminfo=txt_teaminfo.getText();
        //String image = emp.getImage();
        
        
        selectedEmployee.setName(name);
        selectedEmployee.setId(id);
        selectedEmployee.setAge(Integer.parseInt(age));
        selectedEmployee.setGender(gender);
        selectedEmployee.setDate(date);
        selectedEmployee.setLevel(Integer.parseInt(level));
        selectedEmployee.setPos_title(position);
        selectedEmployee.setTeam_info(teaminfo);
        //selectedEmployee.setImage(image);
        
//        for(Employee employee:empList)
//        {
//            if(employee.getId)
//            {
//            employee.setName(name);
//            employee.setId(id);
//            employee.setGender(gender);
//            employee.setDate(date);
//            employee.setAge(Integer.parseInt(age));
//            employee.setLevel(Integer.parseInt(level));
//            employee.setPos_title(position);
//            employee.setTeam_info(teaminfo);
//            }
//        }
        
        
         
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txt_teaminfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_teaminfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_teaminfoActionPerformed

    private void jbtnSaveAfterUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveAfterUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = table.getSelectedRow();
        if(selectedRowIndex<0)
        {
            JOptionPane.showMessageDialog(this,"Please select a row to Update");
            return;
        }
        
        DefaultTableModel mod = (DefaultTableModel)table.getModel();
        
        Employee selectedEmployee = (Employee)mod.getValueAt(selectedRowIndex,0);
        
    
        String name = txt_name.getText();
        String id=txt_id.getText();
        String age=(String)txt_age.getText();
        String gender=(String)txt_gender.getText();
        String date=txt_date.getText();
        String level=txt_level.getText();
        String position=txt_pos.getText();
        String teaminfo=txt_teaminfo.getText();
        //String image = emp.getImage();
        
        
        selectedEmployee.setName(name);
        selectedEmployee.setId(id);
        selectedEmployee.setAge(Integer.parseInt(age));
        selectedEmployee.setGender(gender);
        selectedEmployee.setDate(date);
        selectedEmployee.setLevel(Integer.parseInt(level));
        selectedEmployee.setPos_title(position);
        selectedEmployee.setTeam_info(teaminfo);
        populateTable();
    }//GEN-LAST:event_jbtnSaveAfterUpdateActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mod = (DefaultTableModel)table.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(mod);
        table.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtSearch.getText().trim()));
        
        
    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnSaveAfterUpdate;
    private javax.swing.JLabel lbl_age;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_gender;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_level;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_pic;
    private javax.swing.JLabel lbl_pos;
    private javax.swing.JLabel lbl_search;
    private javax.swing.JLabel lbl_teaminfo;
    private javax.swing.JLabel lbl_view;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_gender;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_level;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_pos;
    private javax.swing.JTextField txt_teaminfo;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
         DefaultTableModel mod = (DefaultTableModel)table.getModel();
         mod.setRowCount(0);
         for(Employee emp:emphistory.getHistory())
         {
             Object[] row = new Object[10];
             row[0]=emp;
             row[1] = emp.getId();
             row[2] = emp.getAge();
             row[3]=emp.getGender();
             row[4] = emp.getLevel();
             row[5] = emp.getTeam_info();
            row[6] = emp.getPos_title();
            row[7] = emp.getDate();
            row[9]=emp.getImage();
            
             mod.addRow(row);
             
         }
    }

    
}
