/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.CommunityWorkArea;

import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import model.City;
import model.Community;
import model.Hospital;
import model.HospitalDirectory;

/**
 *
 * @author Shreya Baliga*/
public class AddCommunity extends javax.swing.JPanel {

    /**
     * Creates new form SystemCreatePatient
     */
    HospitalDirectory hospitalDirectory;
    boolean validationCheck = true;
    boolean emptyValidationStatus = true;
    Community community;
            
    public AddCommunity(Community community) {
        initComponents();
        this.community = community;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblHospName = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        lblHospitalAddress = new javax.swing.JLabel();
        communityField = new javax.swing.JTextField();
        createCommunity = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Hospital");

        lblHospName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblHospName.setText("City");

        cityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityFieldActionPerformed(evt);
            }
        });

        lblHospitalAddress.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblHospitalAddress.setText("Community");

        communityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityFieldActionPerformed(evt);
            }
        });

        createCommunity.setText("Create Community");
        createCommunity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createCommunityMouseClicked(evt);
            }
        });
        createCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCommunityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHospitalAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHospName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cityField, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                            .addComponent(communityField, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createCommunity)
                .addGap(226, 226, 226))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHospName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cityField, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHospitalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(communityField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(createCommunity)
                .addContainerGap(299, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFieldActionPerformed

    private void communityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_communityFieldActionPerformed

    private void createCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCommunityActionPerformed
        // TODO add your handling code here
        
    }//GEN-LAST:event_createCommunityActionPerformed

    private void createCommunityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createCommunityMouseClicked
        // TODO add your handling code here:
         Boolean val = validateFields();
        
        if(val){
            
            String city = cityField.getText();
            String comm = communityField.getText();
            
             this.community.getLstCommunity().forEach((cityName, communityList) ->{
                 if(city.toLowerCase().matches(cityName.toString().toLowerCase())){
                     
                    String data[] = new String[communityList.length+1];
                
                    for(int i =0 ; i < communityList.length; i++){
                        System.out.println(communityList[i]);
                        data[i] = communityList[i];
                    }
                    data[communityList.length] = comm;
                    
                     switch (city.toLowerCase()) {
                        case "newyork":
                             this.community.getLstCommunity().put(City.NewYork, data);
                             break;
                        case "boston":
                             this.community.getLstCommunity().put(City.Boston, data);
                             break;
                        case "southerncalifornia":
                             this.community.getLstCommunity().put(City.SouthernCalifornia, data);
                             break;
                        case "austin":
                             this.community.getLstCommunity().put(City.Austin, data);
                             break;
                         default:
                             throw new AssertionError();
                     }
                    
                 
                 }
             
             });
             
             JOptionPane.showMessageDialog(this, "Community Added successfully",
               "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
             JOptionPane.showMessageDialog(this, "Please enter correct data",
               "Error", JOptionPane.ERROR_MESSAGE);
             
            cityField.setText("");
            communityField.setText("");
         }
        
        
    }//GEN-LAST:event_createCommunityMouseClicked
    
    public Boolean validateFields(){
        
        String city = cityField.getText();
        String comm = communityField.getText();
        
        if(city.length() > 0 && comm.length() > 0 && !hasNumbers(city) && !hasNumbers(comm) ){
        
            return true;
        }
        
        return false;
    };
    
    public Boolean hasNumbers(String data){
        System.out.println(data.matches("[0-9]+"));
        return data.matches("[0-9]+");
    };


    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cityField;
    private javax.swing.JTextField communityField;
    private javax.swing.JButton createCommunity;
    private javax.swing.JLabel lblHospName;
    private javax.swing.JLabel lblHospitalAddress;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
